package br.com.ufrn.bti.concorrente.espatifado.server.comunicacao;

public enum TipoMensagem {
	
	LOGIN, LISTA_MUSICAS, SOLICITA_COMPRA, SOLICITA_PAGAMENTO,
	LOGIN_SUCESSO, LOGIN_FALHA, LISTA_MUSICAS_SUCESSO, LISTA_MUSICAS_FALHA, 
	SOLICITA_COMPRA_SUCESSO, SOLICITA_COMPRA_FALHA, 
	SOLICITA_PAGAMENTO_SUCESSO, SOLICITA_PAGAMENTO_FALHA, REQUISICAO_NAO_TRATAVEL
	
}
